const {
  AndroidConfig,
  withAndroidManifest,
  withAppBuildGradle,
  withProjectBuildGradle,
  withDangerousMod,
  withEntitlementsPlist,
  withXcodeProject,
} = require("expo/config-plugins");
const fs = require("node:fs");
const path = require("node:path");

const APP_GROUP = "group.app.ownday.mobile";
const SNAPSHOT_KEY = "ownday.widget.snapshot.v1";
const PENDING_KEY = "ownday.widget.pending.v1";

const write = (file, content) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
};

function tokenColors(projectRoot) {
  const file = path.join(projectRoot, "..", "..", "packages", "tokens", "dist", "tokens.json");
  if (!fs.existsSync(file)) {
    throw new Error(
      `Widget colours come from ${file}, which is generated by @ownday/tokens and is not in git.
` +
        `It normally exists because pnpm runs that package's prepare script on install.
` +
        `If a clean checkout reaches prebuild without it, run: pnpm --filter "@ownday/mobile^..." build`,
    );
  }
  return JSON.parse(fs.readFileSync(file, "utf8")).color;
}

function androidSource(pkg, colors) {
  let source = fs
    .readFileSync(path.join(__dirname, "OwndayWidget.kt"), "utf8")
    .replaceAll("__PACKAGE__", pkg);
  for (const [key, token] of Object.entries({
    SURFACE: "surface",
    INK: "ink",
    NEUTRAL: "ink-3",
    DONE: "done",
  })) {
    for (const theme of ["light", "dark"])
      source = source.replaceAll(
        "__" + theme.toUpperCase() + "_" + key + "__",
        colors[theme][token],
      );
  }
  return source;
}
function bridgeSource(pkg) {
  return fs
    .readFileSync(path.join(__dirname, "OwndayWidgetBridge.kt"), "utf8")
    .replaceAll("__PACKAGE__", pkg);
}

function withAndroidWidget(config) {
  config = withAppBuildGradle(config, (mod) => {
    if (!mod.modResults.contents.includes("androidx.glance:glance-appwidget"))
      mod.modResults.contents = mod.modResults.contents.replace(
        /dependencies\s*\{/,
        'dependencies {\n    implementation("androidx.glance:glance-appwidget:1.1.1")',
      );
    return mod;
  });
  config = withAndroidManifest(config, (mod) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);
    app.receiver ??= [];
    if (!app.receiver.some((item) => item.$["android:name"] === ".widget.OwndayWidgetReceiver"))
      app.receiver.push({
        $: { "android:name": ".widget.OwndayWidgetReceiver", "android:exported": "true" },
        "intent-filter": [
          { action: [{ $: { "android:name": "android.appwidget.action.APPWIDGET_UPDATE" } }] },
        ],
        "meta-data": [
          {
            $: {
              "android:name": "android.appwidget.provider",
              "android:resource": "@xml/ownday_widget_info",
            },
          },
        ],
      });
    return mod;
  });
  return withDangerousMod(config, [
    "android",
    async (mod) => {
      const root = mod.modRequest.platformProjectRoot;
      const pkg = mod.android?.package ?? config.android.package;
      const java = path.join(root, "app", "src", "main", "java", ...pkg.split("."));
      write(
        path.join(java, "widget", "OwndayWidget.kt"),
        androidSource(`${pkg}.widget`, tokenColors(mod.modRequest.projectRoot)),
      );
      write(path.join(java, "widget", "OwndayWidgetBridge.kt"), bridgeSource(`${pkg}.widget`));
      write(
        path.join(root, "app", "src", "main", "res", "xml", "ownday_widget_info.xml"),
        `<?xml version="1.0" encoding="utf-8"?>\n<appwidget-provider xmlns:android="http://schemas.android.com/apk/res/android" android:minWidth="110dp" android:minHeight="110dp" android:minResizeWidth="110dp" android:minResizeHeight="110dp" android:resizeMode="horizontal|vertical" android:widgetCategory="home_screen" android:updatePeriodMillis="1800000" android:initialLayout="@layout/ownday_widget_loading" />\n`,
      );
      write(
        path.join(root, "app", "src", "main", "res", "layout", "ownday_widget_loading.xml"),
        `<?xml version="1.0" encoding="utf-8"?>\n<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" />\n`,
      );
      const main = path.join(java, "MainApplication.kt");
      let source = fs.readFileSync(main, "utf8");
      if (!source.includes("OwndayWidgetPackage")) {
        source = source.replace(
          /(package [^\n]+\n)/,
          `$1\nimport ${pkg}.widget.OwndayWidgetPackage\n`,
        );
        source = source.replace(
          /PackageList\(this\)\.packages\.apply \{/,
          "PackageList(this).packages.apply {\n              add(OwndayWidgetPackage())",
        );
        fs.writeFileSync(main, source);
      }
      return mod;
    },
  ]);
}

function iosWidgetSource(colors) {
  const encode = (value) => value.replace("#", "0x");
  return fs
    .readFileSync(path.join(__dirname, "OwndayWidget.swift"), "utf8")
    .replaceAll("__APP_GROUP__", APP_GROUP)
    .replaceAll("__SNAPSHOT_KEY__", SNAPSHOT_KEY)
    .replaceAll("__PENDING_KEY__", PENDING_KEY)
    .replaceAll("__LIGHT_SURFACE__", encode(colors.light.surface))
    .replaceAll("__DARK_SURFACE__", encode(colors.dark.surface))
    .replaceAll("__LIGHT_INK__", encode(colors.light.ink))
    .replaceAll("__DARK_INK__", encode(colors.dark.ink))
    .replaceAll("__LIGHT_NEUTRAL__", encode(colors.light["ink-3"]))
    .replaceAll("__DARK_NEUTRAL__", encode(colors.dark["ink-3"]))
    .replaceAll("__LIGHT_DONE__", encode(colors.light.done))
    .replaceAll("__DARK_DONE__", encode(colors.dark.done))
    .replaceAll("__LIGHT_STREAK__", encode(colors.light.streak))
    .replaceAll("__DARK_STREAK__", encode(colors.dark.streak));
}

function withIosWidget(config) {
  config = withEntitlementsPlist(config, (mod) => {
    mod.modResults["com.apple.security.application-groups"] = [APP_GROUP];
    return mod;
  });
  config = withDangerousMod(config, [
    "ios",
    async (mod) => {
      const root = mod.modRequest.platformProjectRoot;
      const dir = path.join(root, "OwndayWidget");
      write(
        path.join(dir, "OwndayWidget.swift"),
        iosWidgetSource(tokenColors(mod.modRequest.projectRoot)),
      );
      write(
        path.join(dir, "Info.plist"),
        `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>
<key>CFBundleDisplayName</key><string>Ownday</string>
<key>CFBundleExecutable</key><string>$(EXECUTABLE_NAME)</string>
<key>CFBundleIdentifier</key><string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
<key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
<key>CFBundleName</key><string>$(PRODUCT_NAME)</string>
<key>CFBundlePackageType</key><string>XPC!</string>
<key>CFBundleShortVersionString</key><string>$(MARKETING_VERSION)</string>
<key>CFBundleVersion</key><string>$(CURRENT_PROJECT_VERSION)</string>
<key>NSExtension</key><dict><key>NSExtensionPointIdentifier</key><string>com.apple.widgetkit-extension</string></dict>
</dict></plist>`,
      );
      write(
        path.join(dir, "OwndayWidget.entitlements"),
        `<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>com.apple.security.application-groups</key><array><string>${APP_GROUP}</string></array></dict></plist>`,
      );
      for (const file of [
        "OwndayWidgetBridge.swift",
        "OwndayWidgetBridge.m",
        "WidgetStorage.swift",
      ]) {
        write(
          path.join(root, config.name, file),
          fs
            .readFileSync(path.join(__dirname, file), "utf8")
            .replaceAll("__APP_GROUP__", APP_GROUP),
        );
      }
      write(
        path.join(dir, "WidgetStorage.swift"),
        fs
          .readFileSync(path.join(__dirname, "WidgetStorage.swift"), "utf8")
          .replaceAll("__APP_GROUP__", APP_GROUP),
      );
      return mod;
    },
  ]);
  return withXcodeProject(config, (mod) => {
    const project = mod.modResults;
    const mainTarget = project.getFirstTarget().uuid;
    const mainGroup = project.getFirstProject().firstProject.mainGroup;
    for (const file of [
      "OwndayWidgetBridge.swift",
      "OwndayWidgetBridge.m",
      "WidgetStorage.swift",
    ]) {
      if (!project.hasFile(config.name + "/" + file))
        project.addSourceFile(config.name + "/" + file, { target: mainTarget }, mainGroup);
    }
    if (project.pbxTargetByName("OwndayWidget") || project.pbxTargetByName('"OwndayWidget"'))
      return mod;
    // A single-target Expo template has no dependency/proxy sections yet.
    project.hash.project.objects.PBXTargetDependency ??= {};
    project.hash.project.objects.PBXContainerItemProxy ??= {};
    const target = project.addTarget(
      "OwndayWidget",
      "app_extension",
      "OwndayWidget",
      `${config.ios.bundleIdentifier}.widget`,
    );
    project.addBuildPhase([], "PBXSourcesBuildPhase", "Sources", target.uuid);
    project.addBuildPhase([], "PBXResourcesBuildPhase", "Resources", target.uuid);
    project.addBuildPhase([], "PBXFrameworksBuildPhase", "Frameworks", target.uuid);
    const group = project.addPbxGroup([], "OwndayWidget", "OwndayWidget");
    project.addToPbxGroup(group.uuid, mainGroup);
    for (const file of ["OwndayWidget.swift", "WidgetStorage.swift"])
      project.addSourceFile(file, { target: target.uuid }, group.uuid);
    for (const file of ["Info.plist", "OwndayWidget.entitlements"])
      project.addFile(file, group.uuid);
    const settings = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(settings)) {
      const build = settings[key];
      if (typeof build === "object" && build.buildSettings?.PRODUCT_NAME === '"OwndayWidget"') {
        Object.assign(build.buildSettings, {
          APPLICATION_EXTENSION_API_ONLY: "YES",
          CODE_SIGN_ENTITLEMENTS: "OwndayWidget/OwndayWidget.entitlements",
          INFOPLIST_FILE: "OwndayWidget/Info.plist",
          IPHONEOS_DEPLOYMENT_TARGET: "17.0",
          LD_RUNPATH_SEARCH_PATHS:
            '"$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"',
          SKIP_INSTALL: "YES",
          SWIFT_VERSION: "5.0",
          MARKETING_VERSION: config.version ?? "1.0.0",
          CURRENT_PROJECT_VERSION: config.ios.buildNumber ?? "1",
          TARGETED_DEVICE_FAMILY: '"1,2"',
        });
      }
    }
    return mod;
  });
}

module.exports = function withOwndayNative(config) {
  config = withProjectBuildGradle(config, (mod) => {
    const marker = "// Ownday: keep CMake staging paths short for Windows + pnpm.";
    if (!mod.modResults.contents.includes(marker)) {
      const staging = `
${marker}
subprojects { nativeProject ->
  ["com.android.library", "com.android.application"].each { pluginId ->
    nativeProject.plugins.withId(pluginId) {
      nativeProject.androidComponents.finalizeDsl { androidDsl ->
        androidDsl.externalNativeBuild.cmake.buildStagingDirectory =
          new File(rootProject.projectDir, "../../../.native-cxx/" + nativeProject.name)
      }
    }
  }
}
`;
      mod.modResults.contents = mod.modResults.contents.replace(
        'apply plugin: "com.facebook.react.rootproject"',
        staging + '\napply plugin: "com.facebook.react.rootproject"',
      );
    }
    return mod;
  });
  return withIosWidget(withAndroidWidget(config));
};
